 export const hadisths = 
  [
    {
        id:1,
        chapter_title:"1/1. Chapter",
        chapter_subtitle:"How the revelation [1] to the Messenger of Allah (may peace be upon him) began.",
        chapter_subtitle_two:"Allah Ta'ala's words in this regard: Indeed, I have sent down to you such revelations as We sent down revelations to Noah and the Prophets after him. (Surah An-Nisa 4/163)",
        hadiths:"حَدَّثَنَا الْحُمَيْدِيُّ عَبْدُ اللَّهِ بْنُ الزُّبَيْرِ، قَالَ حَدَّثَنَا سُفْيَانُ، قَالَ حَدَّثَنَا يَحْيَى بْنُ سَعِيدٍ الأَنْصَارِيُّ، قَالَ أَخْبَرَنِي مُحَمَّدُ بْنُ إِبْرَاهِيمَ التَّيْمِيُّ، أَنَّهُ سَمِعَ عَلْقَمَةَ بْنَ وَقَّاصٍ اللَّيْثِيَّ، يَقُولُ سَمِعْتُ عُمَرَ بْنَ الْخَطَّابِ ـ رضى الله عنه ـ عَلَى الْمِنْبَرِ قَالَ سَمِعْتُ رَسُولَ اللَّهِ صلى الله عليه وسلم يَقُولُ  إِنَّمَا الأَعْمَالُ بِالنِّيَّATِ, وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى, فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى دُنْيَا يُصِيبُهَا اَوْ إِلَى امْرَا َةٍ يَنْكِحُهَا فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ",
        hadiths_author: "Narrated 'Alqamah ibn Waqqas al-Laysi (RA):",
        hadiths_translate: "I heard 'Umar Ibn al-Khattab (may Allah be pleased with him) standing on the pulpit saying: I heard Allah's Messenger (may peace be upon him) say: The deed (will be due) according to the intention. And man will be rewarded according to his intention. So whoever migrates for the purpose of gaining this time or marrying a woman - his migration will be for the purpose for which he migrated. (54, 2529, 3898, 5070, 6689, 6953; Muslim 23/45 AH 1907, Ahmad 168) (Modern Publications-1, Islamic Foundation 1)",
        hadisths_tag: "Sahih Hadith",
        hadith_Number:"1"
    },
    {
        id:2,
        chapter_title:"1/2. Chapter",
        chapter_subtitle_two:"",
        hadiths:"حَدَّثَنَا عَبْدُ اللَّهِ بْنُ يُوسُفَ, قَالَ أَخْبَرَنَا مَالِكٌ, عَنْ هِشَامِ بْنِ عُروَةَ, عَنْ اَبِيهِ, عَنْ عَائِشَةَ أُمِّ الْمُؤْمِنِينَ ـ رضى الله عنهاـ ـ َنَّ الْحَارِثَ بْنَ هِشَامٍ ـ رضى الله عنه ـ سَأَلَ رَسُولَ اللَّهِ صلى الله عليه وسلم فَقَالَ يَا رَسُولَ اللَّهِ كَيْفَ يَأْتِيكَ الْوَحْىُ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم   أَحْيَانًا يَأْتِينِي مِثْلَ صَلْصَلَةِ الْجَرَسِ ـ وَهُوَ أَشَدُّهُ عَلَىَّ ـ فَيْفَسمُ عَنِّي وَقَدْ وَعَيْتُ عَنْهُ م َا قَالَ, وَأَحْيَانًا يَتَمَثَّلُ لِيَ الْمَلَكُ رَجُلاً فَيُكَلِّمُنِي فَأَعِي مَا يَقُولُ . قَالَتْ عَائِشَةُ رضى الله عنها وَلَقَدْ رَأَيْتُهُ يَنْزِلُ عَلَيْهِ الْوَحْىُ فِي الْيَوْمِ الشَّدِيدِ الْبَرْدِ, فَيَفْصِمُ عَنْهُ وَإِنَّ جَبِينَهُ لَيَتَفَصَّدُ عَرَقًا.",
        hadiths_author: "Narrated Umm al-Mu'minin 'Aisha (RA):",
        hadiths_translate: "Harith Ibn Hisham (RA) asked the Messenger of Allah (PBUH), 'O Messenger of Allah! How does revelation come to you?' Allah's Messenger (may peace be upon him) said: [Sometimes it comes to me like a bell. And this is the most painful for me and after that I don't memorize what the angel (angel) says, sometimes the angel speaks to me in the form of a human being. I have not memorized what he said.] 'Aisha (may Allah be pleased with her) said, I saw him during the revelation of revelation during the severe winter. As soon as Wahi was over, sweat would drip from his forehead. (3215; Muslim 43/23, Hah 2333, Ahmad 25307, 26258) (Modern Publications: 2, Islamic Foundation: 2)",
        hadisths_tag: "Sahih Hadith",
        hadith_Number:"2"
    },
    {
        id:3,
        chapter_title:"1/3. Chapter",
        chapter_subtitle_two:"",
        hadiths:"حَدَّثَنَا يَحْيَى بْنُ بُكَيْرٍ, قَالَ حَدَّثَنَا الَّيْثُ, عَنْ عُقَيْلٍ, عَنْ ابْنِ شِهَابٍ, عَنْ عُرْوَةَ بْنِ الزُّيْرِ, عَنْ عَائِشَةَ أُمِّ الْمُؤ ْمِنِينَ, أَنَّهَا قَالَتْ أَوَّلُ مَا بُدِئَ بِهِ رَسُولُ اللَّهِ صلى الله عليه وسلم مِنَ الْوَحْىِ الرُّؤْيَا الصَّالِحَةُ فِي النَّوْمِ, فَكَانَ لَيَرَى رُؤْيَا إِلاَّ جَاءَتْ مِثْلَ فَلَقِ الصُّبْحِ, ثُمَّ حُبِّبَ إِلَيْهِ الْخَلَءُ, وَكَانَ يَخْلُو بِغَارِ حِرَاءٍ فَيَتَحَنَّثُ ِيهِ ـ ـ وَهُوَ التَّعَبُّدُ ـ الَّيَالِيَ ذَوَاتِ الْعَدَدِ قَبْلَ أَنْ يَنْزِعَ إِلَى أَهْلِهِ, وَيَتَوَّدُ لِذَلِكَ, ثُمَّ يَرْجِعُ إِلَى خَدِيجَةَ, فَيَتَزَوَّدُ لِمِثْلِهَاْ حَقُّ وَهُوَ فِي غَارِ حِرَاءٍ, فَجَاءَهُ الْمَلَكُ فَقَالَ اقْرَأْ قَالَ  مَا أَنَا بِقَارِئٍ  قَالَ  فَأَخَذَنِي حَتَّى بَلَغَ مِنِّي الْجَهْدَ, ثُمَّ أَرْسَلَنِي فَقَالَ اقْرَ أْ. قُلْتُ مَا أَنَا بِقَارِئٍ. فَأَخَذَنِي فَغَطَّنِي الثَانِيَةَ حَتَّى بَلَغَ مِنِّي الْجَهْدَ , ثُمَّ أَرْسَلَنِي فَقَالَ اقْرَْ. فَقُلْتُ مَا َنَا بِقَارٍِ. فَأَخَذَنِي فَغَطَّنِي الثَالِثَةَ , ثُمَّ أَرْسَلَنِي فَقَالَ {اقْرَاْ بِاسْم * May Allah bless him and grant him peace هَبَ عَنْهُ الرَّوْعُ, فَقَالَ لِخَدِيجَةَ وَأَخْبَرَهَا الْخَبَرَ  لَقَدْ خَشِيتُ عَلَى نَفْسِي  . تَكْسِبُ الْمَعْدُومَ وَتَقْرِي الضَّيْفَ بِهِ وَرَقَةَ بْنَ نَوْفَلِ بْنِ أَسَدِ بْنِ عَبْدِ الْعُزَّى ابْنَ عَمِّ خَدِيجَةَ। وَكَانَ I مَا شَاءَ اللَّهُ أَنْ يَكْتُبَ اسْمَعْ مِنَ ابْنِ أَخِيكَ. صلى الله عليه وسلم خَبَرَ مَا رَأَى فَقَالَ لَهُ وَرَقَةُ هَذَا النَّامُوسُ الَّذِي نَزَّلَ اللَّهُ عَلَى مُوسَى صلى الله عليه وسلم يَا لَيْتَنِي فِيهَا جَذَعًا, لَيْتَنِي اَكُونُ حَي ًّا إِذْ يُخْرِجُكَ قَوْمُكَ. فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم  أَوَمُخْرِجِيَّ هُمْ . قَالَ نَعَمْ, لَمْ يَأْتِ رَجُلٌ قَطُّ بِمِثْلِ مَا جِئْتَ بِهِ إِلاَّ عُودِيَ, وَإِنْ يُدْرِكْنِي يَوْمُكَ أَنْصُرًكَ نَصْرًا مُؤَزَّرًا. ثُمَّ لَمْ يَنْشَبْ وَرَقَةُ أَنْ تُوُفِّيَ وَفَتَرَ الْوَحْىُ.",
        hadiths_author: "Narrated Umm al-Mu'minin 'Aisha (RA):",
        hadiths_translate: "He said, The first revelation that came to Allah's Messenger (may peace be upon him) was in the form of a real dream while he was asleep. Every dream he saw would be revealed like the light of dawn. After that seclusion became preferable to him and he used to stay in seclusion in the cave of 'Hera'. Thus he would spend several days at a time engrossed in 'Ibadah before returning to his family and taking some provisions with him. Then he would return to Khadijah (RA) and take some food items for the same period. Thus the revelation came to him while staying in the cave of 'Hera'. The angel came to him and said, 'Read'. Allah's Messenger (may peace be upon him) said: [I said, 'I do not know how to read.'' Then he released me and said, 'Read'. I said: I do not know how to read. He hugged me a second time and pressed me in such a way that it hurt me a lot. Then he released me and said, 'Read'. I replied, 'I don't know how to read'. Allah's Messenger (may peace be upon him) said, Then he hugged me for the third time and pressed me. Then he left and said, Recite in the name of your Lord, Who created. Who created man from clotted blood, recite, and your Lord is Most Merciful”- (Surah Alaq 96/1-3). Then the Messenger of Allah (may peace be upon him) returned with this verse. His heart was trembling. He came to Khadija bint Khuwaylid and said, 'Cover me with a cloak', 'Cover me with a cloak'. They covered him with a sheet. Even his doubts disappeared. Then he narrated the incident to Khadija (RA) and said to her, I am worried about myself. Khadija (RA) said, By Allah, never. Allah will never humiliate you. You are kind to your relatives, bear responsibility for the helpless, help the needy, entertain guests and help the needy on the right path. Then Khadijah (RA) went with him to her cousin Waraqah Ibn Nawfal Ibn 'Abdul Asad Ibn 'Abdul 'Uzzah, who had converted to Christianity during the Dark Ages. Who could write in Hebrew and translate the Bible into Hebrew according to Allah's will. He was very old and blind. Khadija (RA) said to him, 'O cousin! Listen to your nephew'. Warakah asked him, 'Nephew! What do you see?' Allah's Messenger (may peace be upon him) narrated everything he saw. Then Waraqah said to him, This is the Messenger whom Allah sent to Musa ('A). Sorry! I wish I had been young that day. Sorry! If only I were alive on the day your people cast you out'. Allah's Messenger (may peace be upon him) said, ['Will they expel me?'] He said, 'Yes, whoever brings something similar (revelation) to what you have brought is treated with hostility. If I am there on that day, I will help you strongly. A few days later, Waraqah ('a) passed away. And Wahi breaks. (3392, 4953, 4955, 4956, 4957,6982; Muslim 1/73 H: 160, Ahmad 26018) (Modern Publications: 3, Islamic Foundation: 3)",
        hadisths_tag: "Sahih Hadith",
        hadith_Number:"3"
    },
    
  ]

